// AUTO-GENERATED SAP HANA MAPPING DSL
NODE SalesOrder FROM VBAK_RAG WITH id = VBELN
NODE Customer FROM KNA1_RAG WITH id = KUNNR
NODE Material FROM VBAP_RAG WITH id = MATNR

EDGE PLACED_BY FROM VBAK_RAG USING KUNNR -> KUNNR
EDGE CONTAINS_ITEM FROM VBAP_RAG USING VBELN -> VBELN
