// AUTO-GENERATED by HanaIntrospector.generate_manifest()
// Do not edit manually — regenerate via:
//   python tools/salt_importer/hana_introspector.py --schema <SCHEMA>

NODE Kna1Rag FROM KNA1_RAG WITH id = KUNNR PROPERTIES (NAME1, ORT01)
NODE VbakRag FROM VBAK_RAG WITH id = VBELN PROPERTIES (KUNNR, NETWR, WAERK, ERDAT)
NODE VbapRag FROM VBAP_RAG WITH id = VBELN PROPERTIES (POSNR, MATNR, ARKTX, NETWR, KWMENG)

EDGE RefersTo_Kna1Rag FROM VBAK_RAG USING KUNNR -> KUNNR
//   -> targets KNA1_RAG(KUNNR) [Confidence: 100.0%]
EDGE RefersTo_VbakRag FROM VBAP_RAG USING VBELN -> VBELN
//   -> targets VBAK_RAG(VBELN) [Confidence: 100.0%]
