import os
import sys
import argparse
from typing import Dict, List, Set, Any
import pandas as pd
from datasets import load_dataset

# We want to identify the exact mapping between these tables.
# The 4 tables in SALT are:
# 1. salesdocuments (Headers)
# 2. salesdocument_items (Line items)
# 3. customers
# 4. addresses

TABLE_NAMES = ["salesdocuments", "salesdocument_items", "customers", "addresses"]
DATASET_NAME = "sap-ai-research/SALT"

def load_data(token: str) -> Dict[str, pd.DataFrame]:
    print(f"Loading {DATASET_NAME} from Hugging Face...")
    dfs = {}
    for table in TABLE_NAMES:
        print(f"  -> Downloading {table}...")
        ds = load_dataset(DATASET_NAME, table, split="train", token=token)
        # Convert to Pandas for easy subset checking
        dfs[table] = ds.to_pandas()
        print(f"     Loaded {len(dfs[table])} rows.")
    return dfs

def identify_unique_columns(dfs: Dict[str, pd.DataFrame]) -> Dict[str, List[str]]:
    unique_cols = {}
    for table, df in dfs.items():
        unique_cols[table] = []
        for col in df.columns:
            if col == "__index_level_0__":
                continue
            # Drop nulls before checking uniqueness
            s = df[col].dropna()
            if len(s) > 0 and len(s.unique()) == len(s):
                unique_cols[table].append(col)
    return unique_cols

def discover_foreign_keys(dfs: Dict[str, pd.DataFrame], unique_cols: Dict[str, List[str]]) -> List[Dict[str, Any]]:
    # We want to find cases where Table A.col_x is a subset of Table B.col_y (where col_y is unique).
    # This implies Table A -> Table B (Foreign Key).
    fks = []
    
    # Pre-compute sets of unique values for target columns to speed up checks
    unique_sets = {}
    for table, cols in unique_cols.items():
        unique_sets[table] = {}
        for col in cols:
            unique_sets[table][col] = set(dfs[table][col].dropna().unique())

    for source_table, source_df in dfs.items():
        for source_col in source_df.columns:
            if source_col == "__index_level_0__":
                continue
                
            # Drop nulls from source
            source_vals = set(source_df[source_col].dropna().unique())
            if not source_vals:
                continue # Empty column or all nulls
                
            # Compare against all unique columns in all OTHER tables
            for target_table, targets in unique_sets.items():
                if source_table == target_table:
                    continue
                    
                for target_col, target_vals in targets.items():
                    # Subset check
                    if source_vals.issubset(target_vals):
                        # Found an FK!
                        fks.append({
                            "source_table": source_table,
                            "source_col": source_col,
                            "target_table": target_table,
                            "target_col": target_col,
                            "confidence": 1.0 # 100% of non-null values matched
                        })
    return fks

def generate_dsl(dfs: Dict[str, pd.DataFrame], unique_cols: Dict[str, List[str]], fks: List[Dict[str, Any]]) -> str:
    dsl = []
    dsl.append("// DRAFT MAPPING DSL")
    dsl.append("// Auto-generated by introspector.py")
    dsl.append("")
    
    # Basic heuristics for picking primary IDs:
    # We look for a unique column whose name is contained in the table name (or vice versa),
    # or just pick the first unique column.
    table_to_id = {}
    
    for table in TABLE_NAMES:
        candidates = unique_cols.get(table, [])
        node_type = "".join([word.capitalize() for word in table.split("_")])
        if table == "salesdocuments": node_type = "SalesDocument"
        if table == "salesdocument_items": node_type = "SalesDocumentItem"
        
        primary_id = candidates[0] if candidates else "UNKNOWN_ID"
        # Try to find a better matching ID based on naming
        for col in candidates:
            if col.lower() in table.lower() or table.lower() in col.lower() or "id" in col.lower():
                primary_id = col
                break
                
        table_to_id[table] = primary_id
        
        dsl.append(f"NODE {node_type} FROM {table} WITH id = {primary_id}")
    
    dsl.append("")
    
    # Generate edges
    for fk in fks:
        source = fk['source_table']
        target = fk['target_table']
        source_col = fk['source_col']
        target_col = fk['target_col']
        
        edge_name = f"RefersTo_{target}"
        if source == "salesdocument_items" and target == "salesdocuments":
            edge_name = "PartOf"
        elif source == "customers" and target == "addresses":
            edge_name = "LocatedAt"
        elif "party" in source_col.lower():
            edge_name = f"HasParty_{source_col}"
            
        dsl.append(f"EDGE {edge_name} FROM {source} USING {source_col} -> {target_col}")
        dsl.append(f"//   -> targets {target}({target_col}) [Confidence: {fk['confidence']*100}%]")
        
    return "\n".join(dsl)

def main():
    token = os.environ.get("HF_TOKEN")
    if not token:
        print("Error: HF_TOKEN environment variable is required.")
        sys.exit(1)
        
    dfs = load_data(token)
    
    print("\nAnalyzing uniqueness...")
    unique_cols = identify_unique_columns(dfs)
    for table, cols in unique_cols.items():
        print(f"  {table}: {len(cols)} unique columns -> {cols}")
        
    print("\nDiscovering foreign keys via value overlap...")
    fks = discover_foreign_keys(dfs, unique_cols)
    for fk in fks:
        print(f"  {fk['source_table']}.{fk['source_col']} -> {fk['target_table']}.{fk['target_col']} (Confidence: {fk['confidence']*100}%)")
        
    print("\nGenerating Draft DSL...\n")
    dsl_output = generate_dsl(dfs, unique_cols, fks)
    
    out_file = "salt_mapping.dsl"
    with open(out_file, "w") as f:
        f.write(dsl_output)
        
    print(dsl_output)
    print(f"\nDraft DSL written to {out_file}")

if __name__ == "__main__":
    main()
