// DRAFT MAPPING DSL
// Auto-generated by introspector.py

NODE SalesDocument FROM salesdocuments WITH id = SALESDOCUMENT
NODE SalesDocumentItem FROM salesdocument_items WITH id = UNKNOWN_ID
NODE Customers FROM customers WITH id = ADDRESSID
NODE Addresses FROM addresses WITH id = ADDRESSID

EDGE PartOf FROM salesdocument_items USING SALESDOCUMENT
//   -> targets salesdocuments(SALESDOCUMENT) [Confidence: 100.0%]
EDGE LocatedAt FROM customers USING ADDRESSID
//   -> targets addresses(ADDRESSID) [Confidence: 100.0%]