use pest::Parser;
use pest_derive::Parser;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Parser)]
#[grammar = "mapping/grammar.pest"]
pub struct DslParser;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct NodeMapping {
    pub label: String,
    pub table: String,
    pub id_column: String,
    pub properties: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct EdgeMapping {
    pub label: String,
    pub table: String,
    pub source_column: String,
    pub target_column: String,
    pub properties: Vec<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Catalog {
    pub nodes: HashMap<String, NodeMapping>,
    pub edges: HashMap<String, EdgeMapping>,
}

impl Catalog {
    pub fn new() -> Self {
        Self::default()
    }

    /// Load the DSL from a string
    pub fn load(dsl: &str) -> anyhow::Result<Self> {
        let mut catalog = Catalog::new();
        let file = DslParser::parse(Rule::file, dsl)?.next().unwrap();

        for statement in file.into_inner() {
            if statement.as_rule() == Rule::EOI {
                break;
            }
            let inner_stmt = statement.into_inner().next().unwrap();
            match inner_stmt.as_rule() {
                Rule::node_def => {
                    let mut inner = inner_stmt.into_inner();
                    let label = inner.next().unwrap().as_str().to_string();
                    let table = inner.next().unwrap().as_str().to_string();
                    let id_column = inner.next().unwrap().as_str().to_string();
                    let mut properties = Vec::new();
                    
                    if let Some(prop_list) = inner.next() {
                        for prop in prop_list.into_inner() {
                            properties.push(prop.as_str().to_string());
                        }
                    }
                    
                    // Allowlist validation for SQL injection prevention
                    Self::validate_identifier(&table)?;
                    Self::validate_identifier(&id_column)?;
                    for prop in &properties {
                        Self::validate_identifier(prop)?;
                    }

                    catalog.nodes.insert(label.clone(), NodeMapping {
                        label,
                        table,
                        id_column,
                        properties,
                    });
                }
                Rule::edge_def => {
                    let mut inner = inner_stmt.into_inner();
                    let label = inner.next().unwrap().as_str().to_string();
                    let table = inner.next().unwrap().as_str().to_string();
                    let source_column = inner.next().unwrap().as_str().to_string();
                    let target_column = inner.next().unwrap().as_str().to_string();
                    let mut properties = Vec::new();
                    
                    if let Some(prop_list) = inner.next() {
                        for prop in prop_list.into_inner() {
                            properties.push(prop.as_str().to_string());
                        }
                    }

                    Self::validate_identifier(&table)?;
                    Self::validate_identifier(&source_column)?;
                    Self::validate_identifier(&target_column)?;
                    for prop in &properties {
                        Self::validate_identifier(prop)?;
                    }

                    catalog.edges.insert(label.clone(), EdgeMapping {
                        label,
                        table,
                        source_column,
                        target_column,
                        properties,
                    });
                }
                _ => {}
            }
        }
        Ok(catalog)
    }

    /// Re-loads the catalog from a confirmed DSL file generated by Phase 0.5 introspector.
    pub fn reload(&mut self, path: &str) -> anyhow::Result<()> {
        let content = std::fs::read_to_string(path)?;
        // Strip comment lines starting with //
        let clean_content: String = content
            .lines()
            .filter(|line| !line.trim().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        let new_catalog = Self::load(&clean_content)?;
        self.nodes = new_catalog.nodes;
        self.edges = new_catalog.edges;
        Ok(())
    }

    /// Prevents SQL injection by restricting table and column names to safe characters
    fn validate_identifier(ident: &str) -> anyhow::Result<()> {
        if ident.is_empty() {
            anyhow::bail!("Identifier cannot be empty");
        }
        for c in ident.chars() {
            if !c.is_ascii_alphanumeric() && c != '_' {
                anyhow::bail!("Invalid identifier format (SQL injection protection): {}", ident);
            }
        }
        Ok(())
    }

    /// Returns a summary of the available nodes and edges for schema introspection
    pub fn summary_for_tenant(&self, _tenant_id: &str) -> (Vec<String>, Vec<String>) {
        let node_labels: Vec<String> = self.nodes.keys().cloned().collect();
        let edge_labels: Vec<String> = self.edges.keys().cloned().collect();
        (node_labels, edge_labels)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_dsl() {
        let input = "
            NODE Material FROM MARA WITH id = MATNR PROPERTIES (MAKTX)
            EDGE SuppliedBy FROM EKPO USING MATNR -> LIFNR PROPERTIES (MENGE)
        ";
        let catalog = Catalog::load(input).unwrap();
        
        let mat = catalog.nodes.get("Material").unwrap();
        assert_eq!(mat.table, "MARA");
        assert_eq!(mat.id_column, "MATNR");
        assert_eq!(mat.properties, vec!["MAKTX"]);
        
        let edge = catalog.edges.get("SuppliedBy").unwrap();
        assert_eq!(edge.table, "EKPO");
        assert_eq!(edge.source_column, "MATNR");
        assert_eq!(edge.target_column, "LIFNR");
        assert_eq!(edge.properties, vec!["MENGE"]);
    }
}
