package test

import (
	"context"
	"crypto/tls"
	"database/sql"
	"fmt"
	"os"
	"testing"
	"time"

	driver "github.com/SAP/go-hdb/driver"
	"github.com/sapiola/sap-cdc-core/internal/connector"
	"github.com/sapiola/sap-cdc-core/internal/event"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.uber.org/zap"
)

func TestHanaCDCIntegration(t *testing.T) {
	host := os.Getenv("SAPIOLA_HANA_HOST")
	if host == "" {
		host = "c83b09c4-2410-4220-ac0a-a3ce11bd0f54.hana.prod-ap21.hanacloud.ondemand.com"
	}
	port := os.Getenv("SAPIOLA_HANA_PORT")
	if port == "" {
		port = "443"
	}
	user := os.Getenv("SAPIOLA_HANA_USER")
	if user == "" {
		user = "DBADMIN"
	}
	password := os.Getenv("SAPIOLA_HANA_PASSWORD")
	if password == "" {
		password = "Pointbreak2504"
	}

	c := driver.NewBasicAuthConnector(fmt.Sprintf("%s:%s", host, port), user, password)
	c.SetTLSConfig(&tls.Config{
		ServerName:         host,
		InsecureSkipVerify: true,
	})

	db := sql.OpenDB(c)
	defer db.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	err := db.PingContext(ctx)
	require.NoError(t, err)

	// Clean up previous run if any
	_, _ = db.ExecContext(ctx, "DROP TABLE DBADMIN.MARA_LOG")

	// 1. Create SLT Logging Table on real HANA
	createDDL := `
		CREATE TABLE DBADMIN.MARA_LOG (
			LSN BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			TRANS_TYPE INT NOT NULL,
			MATNR VARCHAR(18) NOT NULL,
			MAKTX VARCHAR(40)
		)
	`
	_, err = db.ExecContext(ctx, createDDL)
	require.NoError(t, err, "failed to create MARA_LOG")
	defer func() {
		_, _ = db.Exec("DROP TABLE DBADMIN.MARA_LOG")
	}()

	// 2. Insert 10 Test CDC events
	for i := 1; i <= 10; i++ {
		_, err := db.ExecContext(ctx,
			"INSERT INTO DBADMIN.MARA_LOG (TRANS_TYPE, MATNR, MAKTX) VALUES (?, ?, ?)",
			1, // OpInsert
			fmt.Sprintf("MAT-%04d", i),
			fmt.Sprintf("Material Description %d", i),
		)
		require.NoError(t, err)
	}

	logger, _ := zap.NewDevelopment()
	reader := connector.NewSLTReader(db, connector.SLTReaderConfig{
		Tables:    map[string]string{"MARA": "DBADMIN.MARA_LOG"},
		BatchSize: 100,
	}, logger)

	// 3. Read changes from real HANA
	events, err := reader.ReadChanges(ctx, "MARA", 0)
	require.NoError(t, err)
	assert.Len(t, events, 10)

	for idx, ev := range events {
		assert.Equal(t, "MARA", ev.Table)
		assert.Equal(t, fmt.Sprintf("MAT-%04d", idx+1), ev.PrimaryKey)
		assert.Equal(t, event.OpInsert, ev.Operation)
		assert.True(t, ev.LSN > 0)
	}

	// 4. Test Idempotency Filter
	dbPath := t.TempDir() + "/idempotency_hana.db"
	filter, err := event.NewIdempotencyFilter(dbPath)
	require.NoError(t, err)
	defer filter.Close()

	for _, ev := range events {
		isDup, err := filter.IsDuplicate(&ev)
		require.NoError(t, err)
		assert.False(t, isDup, "first processing should not be duplicate")
	}

	// Replaying same events should be detected as duplicate
	for _, ev := range events {
		isDup, err := filter.IsDuplicate(&ev)
		require.NoError(t, err)
		assert.True(t, isDup, "replayed event should be detected as duplicate")
	}

	// Polling with last LSN should return 0 new events from real HANA
	lastLSN := events[len(events)-1].LSN
	newEvents, err := reader.ReadChanges(ctx, "MARA", lastLSN)
	require.NoError(t, err)
	assert.Len(t, newEvents, 0)
}
