// AUTO-GENERATED by HanaIntrospector.generate_manifest()
// Do not edit manually — regenerate via:
//   python tools/salt_importer/hana_introspector.py --schema <SCHEMA>

NODE EkkoPoTest FROM EKKO_PO_TEST WITH id = EBELN PROPERTIES (LIFNR, BEDAT, NETWR)
NODE EkpoPoitemTest FROM EKPO_POITEM_TEST WITH id = EBELN PROPERTIES (EBELP, MATNR, WERKS, MENGE)
NODE Lfa1VendorTest FROM LFA1_VENDOR_TEST WITH id = LIFNR PROPERTIES (NAME1, LAND1)

EDGE RefersTo_Lfa1VendorTest FROM EKKO_PO_TEST USING LIFNR -> LIFNR
//   -> targets LFA1_VENDOR_TEST(LIFNR) [Confidence: 100.0%]
EDGE RefersTo_EkkoPoTest FROM EKPO_POITEM_TEST USING EBELN -> EBELN
//   -> targets EKKO_PO_TEST(EBELN) [Confidence: 100.0%]
